config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:show, :destroy, :edit, :update]
  # resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :image
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    new_bookmark = Bookmark.new(bookmark_params)
    new_bookmark.list_id = params[:list_id]
    if new_bookmark.save
      redirect_to list_path(new_bookmark.list_id)
    else
      render 'lists/show'
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.update(bookmark_params)
    redirect_to list_path(@bookmark.list_id)
  end

  def destroy
    bookmark = Bookmark.find(params[:id])
    bookmark.destroy
    redirect_to list_path(bookmark.list_id)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.where(list_id: @list)
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    List.create(list_params)
    redirect_to lists_path
  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to lists_path
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/edit.html.erb
<div class="container">
  <h1><%= @bookmark.movie.title %></h1>
  <%= simple_form_for @bookmark do |f| %>
    <%= f.input :comment %>
    <%= f.submit "Save changes" %>
  <% end %>
</div>

app/views/bookmarks/show.html.erb
<div class="container">
  <div class="d-flex justify-content-center align-items-start mt-3">

    <%= link_to "BACK", list_path(@bookmark.list_id), class: "btn btn-outline-secondary me-1" %>
    <div class="card">
      <img src="<%= @bookmark.movie.poster_url %>" alt="" class="card-img">
      <div class="hover-wrapper">
        <div class="card-body card-top-white">
          <h2 class="card-title"><%= @bookmark.movie.title %></h2>
          <h6 class="card-subtitle text-muted">Average rating: <%= @bookmark.movie.rating %> / 5</h6>
          <hr>
          <p class="card-text"><%= @bookmark.movie.overview %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,200;0,400;0,600;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name, label: "List Name:" %>
    <%= f.input :image, as: :file %>
    <%= f.submit "Create new list" %>
  <% end %>

app/views/lists/edit.html.erb
<div class="container">
  <%= render "form" %>
  <%= link_to "back", lists_path %>
</div>

app/views/lists/index.html.erb
<div class="container">
  <h2 class="my-5">List of Movies</h2>
  <%= link_to new_list_path do %>
    <p class="m-0 text-end"><i class="far fa-plus-square"></i> Add a list</p>
  <% end %>
  <ul class="cards mt-1">
    <% @lists.each do |list| %>
      <li>
        <%= link_to list_path(list) do %>
            <% if list.image.key %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.image.key, crop: :fill %>')">
            <% else %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_url ("movie_projector.jpg"), crop: :fill %>')">
            <% end %>
              <%= list.name %>
            </div>
        <% end %>
        <div class="d-flex justify-content-end mb-2 card-category-menu">
          <%= link_to edit_list_path(list) do %>
            <i class="far fa-edit"></i>
          <% end %>
          <%= button_to list_path(list), method: :delete, class: "delete-btn" do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="container">
  <%= render "form" %>
  <%= link_to "back", lists_path %>
</div>

app/views/lists/show.html.erb
<% if @list.image.nil? %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.image.key, crop: :fill %>');">
    <div class="container">
      <h1><strong><%= @list.name %></strong>!</h1>
    </div>
  </div>
  <% else %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_url ("movie_projector.jpg"), crop: :fill %>');">
    <div class="container">
      <h1><strong><%= @list.name %></strong>!</h1>
    </div>
  </div>
  <% end %>
<div class="p-3" data-controller='toggle-menu'>
  <div class="container">
    <div class="d-flex justify-content-between align-items-end">
      <%= link_to lists_path, class: "btn btn-outline-secondary btn-small" do %>
        <p class="m-0"><i class="fas fa-undo-alt"></i> BACK</p>
      <% end %>
      <i class="far fa-plus-square togglable-menu-icon" data-action='click->toggle-menu#toggle_form_menu' data-toggle-menu-target="menu_icon"></i>
    </div>
    <div class="d-flex mt-1">
      <ul class="list-group mb-3 flex-grow-1 scrollable-list">
        <% if @bookmarks.empty? %>
          <li class="list-group-item"><strong><span data-action='click->toggle-menu#toggle_form_menu'>Add a movie</span></strong> to start filling out your list</li>
        <% else %>
          <% @bookmarks.each do |bookmark| %>
            <li class="list-group-item list-group-item-action my-2">
              <div class="text-end">
                <%= link_to edit_bookmark_path(bookmark) do %>
                  <i class="far fa-edit"></i>
                <% end %>
                <%= button_to bookmark_path(bookmark), method: :delete, class: "delete-btn" do %>
                  <i class="fas fa-trash-alt custom-icon"></i>
                <% end %>
              </div>
              <%= link_to bookmark_path(bookmark) do %>
                <div class="card-product my-2">
                  <img src=<%= bookmark.movie.poster_url %> />
                    <div class="card-product-infos">
                      <h2><%= bookmark.movie.title %></h2>
                      <p><%= bookmark.comment %></p>
                    </div>
                </div>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>

      <div data-toggle-menu-target="new_movie_form" class="togglable-menu" data-state="closed">
        <%= simple_form_for([@list, @bookmark]) do |f| %>
          <%= f.association :movie, html_input: { class: 'select2', data_controller: "select2" } %>
          <%= f.input :comment %>
          <%= f.submit "add movie to list", class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" height="60vh" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.breweryarts.co.uk%2Fapp%2Fuploads%2F2017%2F11%2FCinema-Ticket-Prices.jpg&f=1&nofb=1);">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <%= link_to "See my lists", lists_path, class: "btn btn-primary" %>
  </div>
</div>